---
- name: "Demostracion de los includes"
  hosts: nodos
  tasks:
    - name: "Mensaje de comienzo de importacion"
      debug:
        msg: "Dara comienzo la importacion de playbooks y tareas"
    
    - name: "Incluir tareas"
      include_tasks: tasks/tasks_imports.yml

- name: "Incluir le playbook bucles" 
  vars:
    paquetes:
      - ipmitool
      - vim
      - mariadb-server
      - blocknotas
  include: playbooks/playbook_errores.yml


