---
- name: "Demostracion de los imports"
  hosts: nodos
  tasks:
    - name: "Mensaje de comienzo de importacion"
      debug:
        msg: "Dara comienzo la importacion de playbooks y tareas"
    - name: "Importar una lista de tareas"
      import_tasks: tasks/tasks_imports.yml

- name: "Importa del playbook"
  import_playbook: playbooks/playbook_bloques02.yml