---
- name: "Demostracion de handlers"
# force_handlers: yes
  hosts: nodos
  vars:
    paquetes:
      - httpd
      - httpd-tools
    fire:
      - http
      - https
 
  tasks:
    - name: "Instalacion de servico httpd"
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ paquetes }}"
      notify: "arrancar_apache"
    
    - name: "Forazar el reinicio de apache"
      meta: flush_handlers
      
    - name: "Habilitar el firewall"
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ fire }}"

    - name: "Deshabilitar el selinux"
      selinux:
        state: disabled

    - name: "Creamos el fichero index"
      file:
        path: /var/www/html/index.html
        mode: 0765
        owner: root
        group: root
        state: touch

    - name: "Insertamos el contenido del index.html"
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <html>
          <head>
          <title>Welcome to Example.com!</title>
          </head>
          <body>
          <h1>Success! The example.com virtual host is working!</h1>
          </body>
          </html>
      notify: "reinicio_servicios_apache"
   
    - name: "Comprobamos que el servidor ha levando correctamente"
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22 
        state: started
      delegate_to: localhost

  handlers:
    - name: "arrancar_apache"
      service:
        name: httpd
        state: started

    - name: "reinicio_apche"
      service:
        name: httpd
        enabled: yes
        state: restarted
      listen: "reinicio_servicios_apache"
    
    - name: "Reinicio de los nodos"
      reboot:
      listen: "reinicio_servicios_apache"