---
- name: "Demostracion de lookups"
  hosts: nodos
  vars:
    test_dict: "{{ lookup('file', 'files/dictionary.json', errors='warn') }}"
    dict_content: "{{ lookup('file', 'files/dictionary.json', errors='warn')|from_json }}"
  
  tasks:
    - debug:
        var: test_dict

    - debug:
        var: dict_content
  